# Generated by Django 5.0.6 on 2024-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.CharField(max_length=15),
        ),
    ]
