# Generated by Django 5.0.6 on 2024-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0002_alter_reserva_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.IntegerField(max_length=4),
        ),
    ]
