# Generated by Django 5.0.6 on 2024-05-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0003_alter_reserva_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente.ambiente'),
        ),
    ]
