# Generated by Django 5.0.6 on 2024-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0005_remove_ambiente_foto_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_final',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
